### ISSUE TITLE
APK is compiled for debug

### ISSUE THREAD

**Issue by IzzySoft** [umutcamliyurt/DroidCrypt#1]
Is there any reason the debug flag is set for the APK? `aapt` shows `application-debuggable` – and I wonder where that comes from, as the Manifest here in the repo does not have it – while the one in the APK does:

```xml
<application android:theme="@7F100227" android:label="@7F0F001C" android:icon="@7F0D0000" android:debuggable="true" android:allowBackup="true" android:supportsRtl="true" android:extractNativeLibs="false" android:appComponentFactory="androidx.core.app.CoreComponentFactory">
```

**Comment by umutcamliyurt** [comment]
Thank you for bringing this to my attention. I've investigated the issue, and it seems that the debug flag in the APK is being set inadvertently during build process. I apologize for any confusion this may have caused.

**Comment by IzzySoft** [comment]
Thanks for your swift reply! So will this be fixed with future releases? Debug should not be enabled for distributions. I'd appreciate a ping here when a release with a non-debug APK is available :smiley:
