### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [umutcamliyurt/DroidCrypt#3]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8150353867#L542

as you tagged https://github.com/umutcamliyurt/DroidCrypt/releases/tag/v1.1 from https://github.com/umutcamliyurt/DroidCrypt/commit/b474aabc779a17defad88386fc6ff0e4c32287aa

but your APK is built from https://github.com/umutcamliyurt/DroidCrypt/commit/8b9a45b86ad1724c95710f2d85f20a07823c7ff8 ?

I don't even see that commit in the list: https://github.com/umutcamliyurt/DroidCrypt/commits/master/

we understand you need to test your commits, but, when ready to release, always build from the tagged commit and upload that APK, not a random one you had around

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/590337084e2a7fc0596aeaeba93a787bcfd4177e

**Comment by umutcamliyurt** [comment]
Fixed this issue

**Comment by licaon-kter** [comment]
Thanks
